#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l vmem=8gb
#PBS -l walltime=1:00:00
#PBS -N dsi-studio-trk2tt

set -e  

trk=$(jq -r .track config.json)

gzip -c ${trk} > data.${trk##*/}.gz

time singularity exec -e docker://dsistudio/dsistudio dsi_studio --action=exp --source=data.${trk##*/}.gz --output=data.${trk##*/}.tt.gz

rm -f data.${trk##*/}.gz

# move file to tt folder
mkdir -p tt
mv data.${trk##*/}.tt.gz tt/tt.gz
