#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l vmem=8gb
#PBS -l walltime=1:00:00
#PBS -N dsi-studio-trk2tt

set -e  

trk=$(jq -r .track config.json)

time singularity exec -e docker://dsistudio/dsistudio dsi_studio --action=exp --source=${trk} --output=data.${trk##*/}.tt.gz


# move file to tt folder
mkdir -p tt
mv data.${trk##*/}.tt.gz tt/tt.gz
